# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel-restful-app:
        container_name: laravel-restful.app
        build:
            context: ./laravel-sail-runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src:/var/www/html'
        networks:
            - sail
        # depends_on:
        #     - mysql
    mailhog:
        image: mailhog/mailhog:v1.0.1
        container_name: mailhog
        restart: "unless-stopped"
        # env_file:
        #     - .env
        # expose:
        #   - "3000"
        ports:
            - "1025:1025"
            - "8025:8025"
        logging:
            driver: "json-file"
            options:
                max-size: "1M"
                max-file: "1000"
        # command: ["-storage=maildir", "-maildir-path=/maildir"]
        privileged: true # Privileged mode could be required to run this container under Windows
        networks:
            - sail
    # mysql:
    #     image: 'mysql/mysql-server:8.0'
    #     ports:
    #         - '${FORWARD_DB_PORT:-3306}:3306'
    #     environment:
    #         MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    #         MYSQL_ROOT_HOST: "%"
    #         MYSQL_DATABASE: '${DB_DATABASE}'
    #         MYSQL_USER: '${DB_USERNAME}'
    #         MYSQL_PASSWORD: '${DB_PASSWORD}'
    #         MYSQL_ALLOW_EMPTY_PASSWORD: 1
    #     volumes:
    #         - 'sailmysql:/var/lib/mysql'
    #     networks:
    #         - sail
    #     healthcheck:
    #         test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
    #         retries: 3
    #         timeout: 5s
networks:
    sail:
        driver: bridge
# volumes:
#     sailmysql:
#         driver: local
